apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend-app
    namespace: backend-app
spec:
   replicas: 3
   strategy:
     type: RollingUpdate
     rollingUpdate:
        maxSurge: 2
        maxUnavailable: 1
   selector:
      matchLabels:
         app: backend
   template:
      metadata:
         name: backendpod
         labels:
           app: backend
      spec:
       containers:
        - name: backend-container
          image:  shivareddy889/backend-app1:latest
          ports:
            - containerPort: 5000
          livenessProbe:
             httpGet:
              path: /healthz
              port: 5000
             initialDelaySeconds: 5
             periodSeconds: 5
             failureThreshold: 3
          readinessProbe:
             httpGet:
               path: /ready
               port: 5000
             initialDelaySeconds: 5
             periodSeconds: 5
             failureThreshold: 3