apiVersion: v1
kind: Service
metadata:
   name: fronend-service
   namespace: frontend-app
spec:
  type: NodePort
  selector: 
         app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
